### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by jmrunge** [gamernetwork/smelted#1]
Hi! I think you should add prerequisites to the Readme.md: 
- Install libxml2-dev, libxslt-dev
- Install pip
- Install lxml via pip

Would have saved me some time! :)

**Comment by lukeinage** [comment]
Thanks! Sorry these weren't in the readme already

**Comment by jmrunge** [comment]
No worries, Im new to phyton thats why it took me a while to figure it out. Thanks for adding it!
