### ISSUE TITLE
Feature request: load/save playlist

### ISSUE THREAD

**Issue by jmrunge** [gamernetwork/smelted#3]
It would be nice if you could save the playlist to a file and load the playlist from a file.  In case the app crashes or perhaps the server has to be restarted, you wouldn't have to recreate the playlist clip by clip, just load the saved playlist.

**Comment by mrmonkington** [comment]
Hi!

They playlist is actually on the melted server, and in theory should reload
when you restart the app.

On 19 March 2015 at 19:53, Juan Martin Runge <notifications@github.com>
wrote:

> It would be nice if you could save the playlist to a file and load the
> playlist from a file. In case the app crashes or perhaps the server has to
> be restarted, you wouldn't have to recreate the playlist clip by clip, just
> load the saved playlist.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamernetwork/smelted/issues/3>.
>



-- 
Mark Kennedy
Technical Director, Gamer Network
www.gamer-network.net

Email: mark@gamer-network.net
Direct: +44 (0)1273 712 554
Office: 3rd Floor, 1 Grand Parade, Brighton, BN2 9QB, UK

**Comment by jmrunge** [comment]
Hey, thanks for your response.  The idea was to save it in case melted crashes too.  But I've seen it is already implemented (menu File, Save, Save As and Open)! It saves an xml and is able to load it again.
Closing this issue, sorry for not taking a deeper look before opening it!
